name: Portainer Stack Redeploy
author: Dzianis Nikifaraŭ
description: Action for request to Portainer API for redeploy stack with pull latest images

inputs:
  portainerUrl:
    description: 'Portainer URL'
    required: true
  accessToken:
    description: 'Portainer access token'
    required: true
  stackId:
    description: 'Stack ID'
    required: true
  endpointId:
    description: 'Endpoint ID'
    required: false
    default: ''
  headers:
    description: 'Custom HTTP Request Headers'
    required: false
    default: '{}'

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'refresh-ccw'
  color: 'blue'
